export const INIT_STATES="STATES.INIT_STATES";
export const INIT_STATEVIEW="STATEVIEW.INIT_STATEVIEW";
export const INIT_STATEUPDATE="STATEEDIT.INITSTATE"
export const LOADING="STATES.LOADING";
export const ERROR="STATES.ERROR";

